spring:
  application:
    name: pium
  web:
    resources:
      static-locations: classpath:/static/

  # PostgreSQL Database Configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/koyebdb}
    username: ${DB_USERNAME:koyebdb}
    password: ${DB_PASSWORD:npg_2iEOCbsTmYA9}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      location: ./uploads
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.admin.pium.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


# Server Configuration
server:
  port: ${PORT:8000}

# Logging Configuration
logging:
  level:
    root: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
